use bevy::platform::collections::{HashMap, HashSet};
use bevy::prelude::*;
use smallvec::SmallVec;

use crate::aabb::Aabb;
use crate::components::{Collider, Solid, Static};
use crate::constants::BROAD_PHASE_MARGIN;
use crate::grid::cells_for_aabb;
use crate::shape::world_aabb;
use crate::static_index::StaticColliderIndex;
use crate::world::{WorldShape, to_world};

/// Per-tick snapshot of one dynamic collider. `shape`/`aabb` are world-space caches the solver
/// translates incrementally; `offset` accumulates corrections for the single Transform
/// write-back at the end of the tick.
pub struct DynamicBody {
    pub entity: Entity,
    pub shape: WorldShape,
    pub aabb: Aabb,
    pub solid: bool,
    pub offset: Vec2,
}

/// Rebuilt every tick; `Vec` allocation retained across ticks.
#[derive(Resource, Default)]
pub struct DynamicBodies {
    pub bodies: Vec<DynamicBody>,
}

/// Who a candidate pair connects. Indices into `DynamicBodies::bodies` / `StaticColliderIndex::entries`.
/// The dynamic side (or lower index) is always the manifold's `a`, so normals point a→b.
pub enum PairBodies {
    DynamicDynamic { a: usize, b: usize },
    DynamicStatic { body: usize, anchor: usize },
}

pub struct CandidatePair {
    pub bodies: PairBodies,
    pub both_solid: bool,
}

/// Candidate pairs for this tick. Rebuilt every tick; allocation retained.
#[derive(Resource, Default)]
pub struct CollisionPairs {
    pub pairs: Vec<CandidatePair>,
}

/// Broad phase: snapshot dynamics (one `to_world` + AABB each), then collect candidate pairs
/// with an AABB early-out inflated by `BROAD_PHASE_MARGIN` — near-contacts enter the list so
/// mid-solve corrections can't push a body into an unpaired neighbor. Static-static pairs are
/// never generated by construction. The margin is applied once per test; dynamic grid insertion
/// uses inflated cells so co-residency is a superset of the inflated overlap test.
pub fn collect_collision_pairs(
    mut bodies: ResMut<DynamicBodies>,
    mut pairs: ResMut<CollisionPairs>,
    statics: Res<StaticColliderIndex>,
    query: Query<(Entity, &Transform, &Collider, Has<Solid>), Without<Static>>,
    mut dynamic_grid: Local<HashMap<IVec2, Vec<usize>>>,
    mut seen: Local<HashSet<(usize, usize)>>,
) {
    bodies.bodies.clear();
    pairs.pairs.clear();
    // Keep allocations for cells occupied last tick; drop cells that sat empty a full tick,
    // so the map is bounded by current occupancy rather than everywhere dynamics have been.
    dynamic_grid.retain(|_, cell| {
        let keep = !cell.is_empty();
        cell.clear();
        keep
    });
    seen.clear();

    for (entity, transform, collider, solid) in &query {
        bodies.bodies.push(DynamicBody {
            entity,
            shape: to_world(&collider.shape, transform),
            aabb: world_aabb(&collider.shape, transform),
            solid,
            offset: Vec2::ZERO,
        });
    }

    for (body_idx, body) in bodies.bodies.iter().enumerate() {
        let inflated = body.aabb.inflated(BROAD_PHASE_MARGIN);

        // vs statics: a static spans many cells — dedup its entry indices before testing.
        let mut anchors: SmallVec<[usize; 8]> = SmallVec::new();
        for cell in cells_for_aabb(&inflated) {
            if let Some(entries) = statics.cells.get(&cell) {
                anchors.extend_from_slice(entries);
            }
        }
        anchors.sort_unstable();
        anchors.dedup();
        for anchor in anchors {
            let entry = &statics.entries[anchor];
            if inflated.overlaps(&entry.aabb) {
                pairs.pairs.push(CandidatePair {
                    bodies: PairBodies::DynamicStatic {
                        body: body_idx,
                        anchor,
                    },
                    both_solid: body.solid && entry.solid,
                });
            }
        }

        for cell in cells_for_aabb(&inflated) {
            dynamic_grid.entry(cell).or_default().push(body_idx);
        }
    }

    for cell_bodies in dynamic_grid.values() {
        for (i, &a) in cell_bodies.iter().enumerate() {
            for &b in &cell_bodies[i + 1..] {
                let key = if a < b { (a, b) } else { (b, a) };
                if !seen.insert(key) {
                    continue;
                }
                let (a, b) = key;
                let body_a = &bodies.bodies[a];
                let body_b = &bodies.bodies[b];
                if body_a
                    .aabb
                    .inflated(BROAD_PHASE_MARGIN)
                    .overlaps(&body_b.aabb)
                {
                    pairs.pairs.push(CandidatePair {
                        bodies: PairBodies::DynamicDynamic { a, b },
                        both_solid: body_a.solid && body_b.solid,
                    });
                }
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::static_index::maintain_static_index;

    fn app() -> App {
        let mut app = App::new();
        app.init_resource::<StaticColliderIndex>()
            .init_resource::<DynamicBodies>()
            .init_resource::<CollisionPairs>()
            .add_systems(
                Update,
                (maintain_static_index, collect_collision_pairs).chain(),
            );
        app
    }

    fn spawn_box(app: &mut App, pos: Vec2, half: f32, is_static: bool) -> Entity {
        let mut e = app.world_mut().spawn((
            Transform::from_xyz(pos.x, pos.y, 0.0),
            Collider::obb(Vec2::splat(half)),
            Solid,
        ));
        if is_static {
            e.insert(Static);
        }
        e.id()
    }

    fn pair_count(app: &App) -> usize {
        app.world().resource::<CollisionPairs>().pairs.len()
    }

    #[test]
    fn multi_cell_pair_generated_once() {
        let mut app = app();
        // Two overlapping 100u-half boxes span several 80u cells each — still one pair.
        spawn_box(&mut app, Vec2::ZERO, 100.0, false);
        spawn_box(&mut app, Vec2::new(50.0, 50.0), 100.0, false);
        app.update();
        assert_eq!(pair_count(&app), 1);
    }

    #[test]
    fn near_contact_within_margin_enters_list() {
        let mut app = app();
        spawn_box(&mut app, Vec2::ZERO, 10.0, false);
        // Gap of 4u < BROAD_PHASE_MARGIN (8) — not touching, but a candidate.
        spawn_box(&mut app, Vec2::new(24.0, 0.0), 10.0, true);
        app.update();
        assert_eq!(pair_count(&app), 1);
    }

    #[test]
    fn beyond_margin_not_paired() {
        let mut app = app();
        spawn_box(&mut app, Vec2::ZERO, 10.0, false);
        // Gap of 12u > margin.
        spawn_box(&mut app, Vec2::new(32.0, 0.0), 10.0, true);
        app.update();
        assert_eq!(pair_count(&app), 0);
    }

    #[test]
    fn static_static_never_paired() {
        let mut app = app();
        spawn_box(&mut app, Vec2::ZERO, 10.0, true);
        spawn_box(&mut app, Vec2::new(5.0, 0.0), 10.0, true); // deeply overlapping statics
        app.update();
        assert_eq!(pair_count(&app), 0);
    }
}
